name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Install dependencies
        run: npm ci

      - name: Check config files before build
        run: |
          echo "=== Config files before build ==="
          ls -la next.config.* || echo "No next.config files found"
          echo ""
          echo "=== Content of next.config.ts ==="
          cat next.config.ts

      - name: Build with Next.js
        run: npm run build

      - name: Check what was created
        run: |
          echo "=== Config files after build ==="
          ls -la next.config.* || echo "No next.config files found"
          echo ""
          echo "=== Looking for out directory ==="
          if [ -d "out" ]; then
            echo "✓ out directory exists!"
            ls -la out/
          else
            echo "✗ out directory NOT found"
            echo "Checking .next for export marker..."
            cat .next/export-marker.json || echo "No export marker"
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
